### ISSUE TITLE
Remove capture/non-captured logic?

### ISSUE THREAD

**Issue by clementgallet** [TASEmulators/pcem#4]
PCem has captured and non-captured mode, so that users can escape the system and use right-click for menu. When running with libTAS, non-captured mode becomes useless, because we don't and can't use the right-click menu, and also because libTAS prevents the mouse grabbing.

So, should we disable non-captured mode? That would mean that users won't be able to use PCem much outside of libTAS though.

**Comment by vadosnaprimer** [comment]
I think as long as it doesn't introduce problems, we want to minimize the amount of differences we introduce compared to upstream. So it should be ok to leave this mode as available. Probably to allow free use of it outside libtas, which is sometimes easier.

**Comment by vadosnaprimer** [comment]
Closing until we find out we actually need this tweak.
